org: adamildk
app: lambda-api
service: lambda-api

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1600
  timeout: 30
  region: eu-central-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  CHROME_AWS_LAYER_ARN: arn:aws:lambda:eu-central-1:764866452798:layer:chrome-aws-lambda:31

functions:
  notionGet:
    handler: src/integrations/notion/get.handler
    events:
      - http:
          path: notion/get
          method: get
  notionPost:
    handler: src/integrations/notion/post.handler
    events:
      - http:
          path: notion/post
          method: post
  notionInitialize:
    layers: ${self:custom.CHROME_AWS_LAYER_ARN}
    handler: src/integrations/notion/initialize.handler
    events:
      - http:
          path: notion/initialize
          method: post
