org: adamildk
app: lambda-api
service: lambda-api

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 1600
  timeout: 50
  region: eu-central-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  CHROME_AWS_LAYER_ARN: arn:aws:lambda:eu-central-1:764866452798:layer:chrome-aws-lambda:31

functions:
  # Notion
  notionScan:
    layers: ${self:custom.CHROME_AWS_LAYER_ARN}
    handler: src/integrations/notion/scan.handler
    events:
      - http:
          path: notion/scan
          method: post
  # Asana
  asanaScan:
    layers: ${self:custom.CHROME_AWS_LAYER_ARN}
    handler: src/integrations/asana/scan.handler
    events:
      - http:
          path: asana/scan
          method: post
  # Figma
  figmaScan:
    layers: ${self:custom.CHROME_AWS_LAYER_ARN}
    handler: src/integrations/figma/scan.handler
    events:
      - http:
          path: figma/scan
          method: post
